name: Deploy to VPS

on:
  workflow_run:
    workflows:
      - 'Java CI'
    types:
      - completed
jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Info
        run: echo 'The triggering workflow passed' | echo ${{ secrets.AWS_SSH_KEY }}
      - name: Upload application
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP_ADDRESS }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: "my-app.jar"
          target: "~/source"

      - name: Start Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.API_IP_ADDRESS }}
          username: ${{ secrets.API_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            sudo /etc/init.d/my-app stop
            mv ~/source/my-app.jar ~/source/my-app-old.jar
            mv ~/source/my-app-latest.jar ~/source/my-app.jar
            sudo rm -rf /etc/init.d/my-app
            sudo ln -s -f ~/source/my-app.jar /etc/init.d/my-app
            sudo /etc/init.d/my-app start
            rm ~/source/my-app-old.jar

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
